/// Flutter icons Shopping
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shopping
///      fonts:
///       - asset: fonts/Shopping.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Shopping {
  Shopping._();

  static const _kFontFam = 'Shopping';

  static const IconData shopping_bag_01 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData path_263 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xf175, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xf176, fontFamily: _kFontFam);
}
